### ISSUE TITLE
first steps

### ISSUE THREAD

**Issue by edublancas** [ploomber/sql#1]
1. deploy sample jupyterbook
2. migrate content from colab notebooks to this site so it's displayed on the website
3. define content draft (number of lessons and topics)
4. configure binder and colab (ask @edublancas for help)

**Comment by edublancas** [comment]
I merged the first PR, you can now deploy to readthedocs.

you need to add a config file like this (ignore the was s3 part): https://github.com/ploomber/jupysql/blob/master/.readthedocs.yml

I gave you admin permissions, so you can now push directly to main (so you can quickly tweak the readthedocs config file), for other contributions, please open a PR.

**Comment by edublancas** [comment]
@lfunderburk

**Comment by lfunderburk** [comment]
@edublancas it looks like the main branch is still protected so I can't make pushes directly on the repo's main branch

**Comment by edublancas** [comment]
what error are you getting?

**Comment by lfunderburk** [comment]
It just says "main branch is protected"

Also, I am ready for this

configure binder and colab

How did you set it up?

**Comment by edublancas** [comment]
> It just says "main branch is protected"

can you try again? I elevated your permissions

> configure binder and colab

for colab, check out the jupyter-book documentation

for binder, check this: https://github.com/ploomber/jupysql/blob/master/doc/conf.py

note that by default, jupyter-book generates a _config.yml, but you can export it to conf.py. check this out: https://github.com/ploomber/contributing/blob/29b5fcd8c66ee17b68b2a8144bc1e71348bafa41/maintainer/jupyter-book.md#dynamic-binder-links

**Comment by lfunderburk** [comment]
Tested again. It works now. Thank you!
