### ISSUE TITLE
set fail on warning to true

### ISSUE THREAD

**Issue by edublancas** [ploomber/sql#19]
In https://github.com/ploomber/sql/pull/17, I fixed deployment to readthedocs, however, I set `fail_on_warning: false` in `.readthedocs.yml` since the building process is throwing a lot of warnings, we should fix them and then set `fail_on_warning: true`

**Comment by lfunderburk** [comment]
Hi @edublancas 
Can you share what warnings it is throwing?

**Comment by edublancas** [comment]
you can see them in the readthedocs console: https://readthedocs.org/projects/ploomber-sql/builds/20958179/

in the last step, you'll see the logs, and all the warnings

**Comment by lfunderburk** [comment]
Ok 
I can tackle these
Self assigning

**Comment by lfunderburk** [comment]
Completed task. 

Need to ensure we have a CI action to build the jupyter book for each pr
