### ISSUE TITLE
Identify dataset for last 2 tutorials in intro to SQL bundle

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#23]
Tutorial topics:

Joining data in SQL
Combining data from multiple tables

Goal: identify datasets for that can be used in the tutorials above

cc @TegveerG @jpjon

**Comment by TegveerG** [comment]
@lfunderburk Hi, Jonathan and I finalized the datasets we want to work with for the remaining 2 sections. The data can be found here:

https://github.com/TegveerG/sql-course-data

I also have modified the README.md for users' convenience and it's public for improving it. We shall use the .csv files in the cleaned_data/ folder for building the course materials. The raw_data/ is also provided for users to dive deeper and query themselves

**Comment by TegveerG** [comment]
@lfunderburk marked this issue as done in Asana, can move to close

**Comment by jpjon** [comment]
The .py script to download the data is complete and is being mutually used for both the 'joining' and 'combining' section.

**Comment by lfunderburk** [comment]
Completed
