### ISSUE TITLE
Write tutorial: SQL query visualization with ggplot

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#45]
**Write tutorial: SQL query visualization with ggplot**

When writing these tutorials, try to use the database with multiple tables, and take some of the operations that were used during the joins, aggregate, subqueries and advanced aggregate units.

Relevant documentation, integrate into tutorial in the following order

1. %sqlplot: https://jupysql.ploomber.io/en/latest/api/magic-plot.html
2. ggplot api: https://jupysql.ploomber.io/en/latest/user-guide/ggplot.html
3. interactive ggplot: https://jupysql.ploomber.io/en/latest/howto/ggplot-interact.html

Starter file https://github.com/ploomber/sql/blob/main/course-material/visualizing-your-sql-queries/plotting-with-ggplot.md

**Comment by TegveerG** [comment]
Had a question: how will adding `%sqlplot` in this section pertain to ggplot API?
