### ISSUE TITLE
Identify data sources (api or github.raw data sources) that are updated periodically

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#62]
Try to identify a dataset that meets:

1. [Strong requirement] Tabular data with a combination of numerical and categorical information
2. [Optional but would be really nice] Look for larger datasets (at least 200,000 entries)
3. [Strongly recommended, but if can't find no worries, lower frequency works too]. Look for datasets that are updated regularly (biweekly, weekly ideally)
4. [Strong requirement] Datasets that are open - look into their licenses, the dataset should be free and can be used for educational purposes

**Comment by lfunderburk** [comment]
Context:

The goal of this is to design an ETL process with the dataset that we can use for the packaging, dashboard and deployment components of this course. 


![](https://files.slack.com/files-pri/T03DX4SDX7E-F05GKMQBW83/packaging-content.jpg)

**Comment by lfunderburk** [comment]
**Candidate two**: Vehicle fuel consumption dataset

**Link:** https://open.canada.ca/data/en/dataset/98f1a129-f628-4ce4-b24d-6f16bf24dd64
**License (open and well defined):** https://open.canada.ca/en/open-government-licence-canada
**Content:** information about CO2 emissions, fuel consumption for three kinds of vehicles (fuel based, hybrid and electric)
**Updated:** once a month
**Number of records as of today:** ~27500
**Note** There are lots of open datasets on that page, usually with thousands of records. 

Scripts for data download: this is a data download and data cleaning script I built to parse and handle the records. We could repurpose it for the ETL pipeline. https://github.com/lfunderburk/fuel-electric-hybrid-vehicle-ml/blob/main/src/data/data_extraction.py

**Comment by jpjon** [comment]
I like the vehicle fuel consumption dataset because it requires very little domain knowledge. It also seems to indefinitely not require an API key when requests are called.

**Comment by TegveerG** [comment]
Yea agreed @jpjon I like the emissions dataset as well, would be easier to get up to speed with it. Although I could only see that they update it "as needed", maybe @lfunderburk since you have worked with it would know about the monthly periodicity. Another data source I thought of was NOAA Daily Summaries that we could collect for NYC for example. It does require an API key and I have the script for it, but the emissions data seems like the best out of all the three discussed.

**Comment by lfunderburk** [comment]
Ok 
closing this issue
