### ISSUE TITLE
Begin ETL process

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#63]
![packaging-content](https://github.com/ploomber/sql/assets/13559004/094c7935-724d-4d22-b5e5-6734b447473b)

This script is currently extracting data sources from multiple sources, cleaning and saving into a csv

https://github.com/lfunderburk/fuel-electric-hybrid-vehicle-ml/blob/main/src/data/data_extraction.py

**Goal 1**
The goal is to modify this script so that it only extracts, cleans and saves data from the CO2 vehicle emissions data source 

Link: https://open.canada.ca/data/en/dataset/98f1a129-f628-4ce4-b24d-6f16bf24dd64
License (open and well defined): https://open.canada.ca/en/open-government-licence-canada

**Goal 2**

Start identifying how the script works:

1. What dependencies are needed
2. What folder structure does it assume
3. What are the files it obtains
4. Suggest methods to improve the workflow it has

**Goal 3**

Modify script, incorporate jupysql to save the clean data into a database (sqlite, duckdb)

**Comment by lfunderburk** [comment]
This is blocked by https://github.com/ploomber/sql/issues/64 

Please hold until this is resolved before contributing. 

You can start with identifying only the relevant pieces of the script shared

**Comment by lfunderburk** [comment]
The following two functions and applications can be deleted

```
def extract_stats_can_data(stats_can_url: str, folder_path:str, file_name : str) -> None:
    """
    This function extracts data from StatsCan and saves it into a CSV file
    Parameters:
        stats_can_url (str): URL to StatsCan data
        folder_path (str): Path to folder where data will be saved
        file_name (str): Name of file where data will be saved
    Returns:
        None
    """
    resp = urlopen(stats_can_url)
    myzip = ZipFile(BytesIO(resp.read()))
    extraction_file_name = [item for item in myzip.namelist() if "MetaData" not in item]
    stats_can_csv = myzip.open(extraction_file_name[0])
    stats_can_df = pd.read_csv(stats_can_csv)
    stats_can_df.drop(columns=['DGUID',
                             'UOM_ID',
                             'SCALAR_ID',
                             'VECTOR',
                             'COORDINATE',
                             'STATUS',
                             'SYMBOL',
                             'TERMINATED',
                             'DECIMALS'], inplace=True)



    stats_can_df.to_csv(Path(folder_path, file_name))


def process_json_car_sales(json_filen_name, path) -> list():
    """
    This function processes the JSON file containing car sales data and returns a dataframe
    Parameters:
        json_file_name (str): Name of JSON file
        path (str): Path to folder where JSON file is located
    Returns:
        df_expanded_long (pd.DataFrame): Dataframe containing car sales data in long format
        df_expanded_wide (pd.DataFrame): Dataframe containing car sales data in wide format

    """
    json_df = pd.read_json(Path(path,json_filen_name)).set_index("model")
    json_df.dropna(how="all", inplace=True)
    
    # Wide format
    wide_df = pd.read_json(Path(path,json_filen_name))
    df_expanded_wide = wide_df.join(wide_df.reset_index()['model'].str.split(' ', 1, expand=True).rename(columns={0:'make', 1:'model_'})).drop(columns=["model"])
    df_expanded_wide['year'] = json_filen_name.split("_")[0]

    # long format
    long_format_df = pd.DataFrame(json_df.T.unstack()).reset_index().rename(columns={"level_1":"month",0:"number_units_sold"})
    df_expanded_long = long_format_df.join(long_format_df.reset_index()['model'].str.split(' ', 1, expand=True).rename(columns={0:'make', 1:'model_'})).drop(columns=["model"])
    df_expanded_long['year'] = json_filen_name.split("_")[0]
    df_expanded_long['month']  = df_expanded_long['month'].map(month_dic) 

    # Remove ',' from number_units_sold
    df_expanded_long['number_units_sold'] = df_expanded_long['number_units_sold'].str.replace(",","")

    # Transform month and number_units_sold to int 
    df_expanded_long['month'] = df_expanded_long['month'].astype('int')
    df_expanded_long['number_units_sold'] = df_expanded_long['number_units_sold'].astype('int')

    # Combine 'month' and 'year' into 'date' column and convert to datetime in format YYYY-MM 
    df_expanded_long['date'] = df_expanded_long['year'].astype(str) + "-" + df_expanded_long['month'].astype(str)
    # Convert 'date' to datetime
    df_expanded_long['date'] = pd.to_datetime(df_expanded_long['date'], format='%Y-%m')
    # Drop 'month' and 'year' columns
    df_expanded_long.drop(columns=['month','year'], inplace=True)

    return df_expanded_long, df_expanded_wide
```

**Comment by lfunderburk** [comment]
Added directory structure and script to main

You can execute from
sql/pipeline

python src/datadownload.py

**Comment by jpjon** [comment]
For Goal 1, do you mean adjusting the data download script to only output something like `1995_today_vehicle_fuel_consumption.csv`? 

In that case, ignore the electric and hyprid data sets and download all other files called `Fuel Consumption Ratings` and concatenate/clean them?

**Comment by lfunderburk** [comment]
1995_today_vehicle_fuel_consumption.csv

has all the merged and cleaned files

the processed folder has the cleaned data for the three kinds of vehicles

**Comment by lfunderburk** [comment]
The task could be do decide:

1. Do we want to merge hybrid to electric to fuel only
2. Do we want three tables (one for each)

What are your thoughts?

**Comment by jpjon** [comment]
I agree with point 2. I guess my question is that for Goal 1, it seems that we are already doing that with the `datadownload.py` script. 

The script only references this data source: https://open.canada.ca/data/en/dataset/98f1a129-f628-4ce4-b24d-6f16bf24dd64 

Can you help me understand what needs to be modified in the script?

**Comment by lfunderburk** [comment]
Instead of saving three csv files, ideally we get it to load things to a database

We could still have a file for data download that saves to csv
But then we'd need a Jupyter notebook for creating and loading the tables

ideally we have one script

**Comment by lfunderburk** [comment]
The idea is we will be able to schedule this on an ec2 instance with a docker container
so the cleaner the set up is the better

**Comment by jpjon** [comment]
I see, got it. I'll look into how the script will load the data in three separate databases in DuckDB.

**Comment by lfunderburk** [comment]
Thank you. Assigned you on Asana
