### ISSUE TITLE
Create tutorial for: "Making your first query"

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#7]
## Helper information

**Topic** Making your first query

**Starter markdown file**

https://github.com/ploomber/sql/blob/main/course-material/intro-to-sql/making-your-first-query.md

**Sample tutorial** 

https://github.com/ploomber/sql/blob/main/course-material/exploratory-data-analysis-with-sql/absenteeism-dataset.md

Sample Google Colab https://tinyurl.com/jupysql-day1-prod

**Relevant documentation**

You can use the following documentation to get familiar with the functionality supported:

https://jupysql.ploomber.io/en/latest/quick-start.html#querying

## Task:

Write a tutorial that includes an exercise with hints. Assume the tutorial is written for someone who would launch the notebook on Google Colab or Binder, and would interact with the tutorial via the Jupyter notebook. Ensure to include an introduction to the problem explored. Link resources you think are relevant.

**Comment by jpjon** [comment]
The PR is ready for review

**Comment by lfunderburk** [comment]
This has been resolved and merged to main
