### ISSUE TITLE
Create dashboard for CO2 emissions dataset

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#77]
Goal is twofold:

1. Develop a dashboard using Voila, JupySQL, and the DuckDB database with CO2 emissions (4 tables, plus interesting queries)
2. Write about it

To keep things simple, please use this example to guide you

https://github.com/ploomber/doc/blob/main/examples/quickstart/notebook.ipynb

There will be two products associated with the PR and issue:

**a. A jupyter notebook that can be executed into a dashboard with Voila**
**b. A blogpost** 

The blog should have

1. Introduction to Voila (what it is and how it connects to Jupyter notebooks, link their docs and github)
2. Introduction to the questions your dashboard will address
3. Explain how it is connected to the ETL process (i.e. it is taking the clean and curated tables to generate visualizations)
4. Explain how your dashboard is structured (ensure to use ipywidgets to add interactivity)
5. How to launch the dashboard locally
6. Interesting insights about the data

**Comment by lfunderburk** [comment]
Hi @TegveerG 

Did doc clean up

Can you merge main into your branch?

https://github.com/ploomber/sql/blob/main/docs/intro-to-dashboards-and-apps/connecting-etl-to-dashboard-with-voila.md

**Comment by TegveerG** [comment]
Yep shall do it now
