### ISSUE TITLE
Improve layout and feel of current voila dashboard

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/sql#82]
The existing dashboard has set ground work for a solid voila app for getting data insights

It would be good to explore ways to make the plots look more aligned (for example the plot size varies) 

**Task**
Explore tools compatible with Voila that would allow you to structure it into a dashboard format (plots and tables side by side or in a grid)

One tool to explore

https://github.com/voila-dashboards/voila-gridstack

**Goal**

Improve the aesthetics and user experience, help make the dashboard fit into the screen, minimize the need for scrolling

**Comment by jpjon** [comment]
Please reference this issue: https://github.com/ploomber/cloud-backend/issues/152

We were able to run gridstack locally. However, ploomber cloud does not currently support it.
